name = dead_explosion
title = Dead Explosion
description = Adds an explosion effect when the player dies
author = Kenneth404040
depends = default
min_luanti_version = 5.15
supported_games = minetest_game
